services:

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  backend:
    build: tests/.
    ports:
      - "8000:8000"

  donkey:
    depends_on:
      - backend
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      ENV: docker
    build: .
    ports:
      - "3000:3000"
